_base_: base.yml

experiment_name: "resnet_baseline"

model:
  type: "resnet_baseline"
  params:
    resnet_channels: [32, 64, 128]
    kernel_size: 7
    dropout: 0.4

training:
  learning_rate: 0.001
  epochs: 120